[package]
name = "backend_llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm13-0"] }
anyhow = { version = "1.0", default-features = false }
tempfile = "3"
err-derive = "0.3.0"