[package]
name = "backend_core"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_ecma_parser = { version = "=0.78.5", features = ["typescript"] }
swc_ecma_ast = { version = "=0.58" }
swc_common = { version = "0.14.0", features = ["tty-emitter"] }