name: Build

on:
  push:
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'src/**'
  pull_request:
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'src/**'

jobs:
  linux_gnu_x86:
    name: Debian X86 - Rust ${{ matrix.rust }}
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        rust: [1.56.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM 13
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt
      - name: Run cargo fmt cubestore
        uses: actions-rs/cargo@v1
        with:
          command: fmt
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -j 4

  apple_x86:
    name: macOS X86 Rust ${{ matrix.rust }}
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        rust: [1.56.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM 13
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt
      - name: Run cargo fmt cubestore
        uses: actions-rs/cargo@v1
        with:
          command: fmt
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -j 4